---
services:
  clean:
    extends:
      file: ../assets/container/compose.yml
      service: clean

  app:
    extends:
      file: ../assets/container/compose.yml
      service: compile
    environment:
      PROJECT: s2-app1
      INPUT_FILE: rapport/00-rapport.tex
      OUTPUT_FILE: chab1704.pdf

  app-watch:
    extends:
      service: app
    environment:
      REALTIME: true
